# DS Main Project 
#### Student Name: Muthupandian S
#### Batch: DSAN01
#### Project Title: Next Word Prediction Using LSTM
#### Project Category: Deep Learning / NLP / LSTM 
#### Submission Date:

<font color="197AA6" size=5px><b>Stage 1-Data selection , EDA, data cleaning ,data preprocessing</b></font>

In [75]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np
import requests
import pandas as pd
import time
import re
import ast

# Dataset Selection & Understanding

Dataset Source: "https://datasets-server.huggingface.co/rows"

In [76]:
url = "https://datasets-server.huggingface.co/rows"

recipes = []

for offset in range(0, 5000, 100):

    params = {
        "dataset": "Mahimas/recipenlg",
        "config": "default",
        "split": "train",
        "offset": offset,
        "length": 100
    }

    response = requests.get(url, params=params)

    if response.status_code != 200:
        print("Error:", response.status_code)
        break

    data = response.json()

    for item in data["rows"]:
        recipes.append(item["row"])

    print(f"Downloaded: {len(recipes)}")

    time.sleep(0.2)

Downloaded: 100
Downloaded: 200
Downloaded: 300
Downloaded: 400
Downloaded: 500
Downloaded: 600
Downloaded: 700
Downloaded: 800
Downloaded: 900
Downloaded: 1000
Downloaded: 1100
Downloaded: 1200
Downloaded: 1300
Downloaded: 1400
Downloaded: 1500
Downloaded: 1600
Downloaded: 1700
Downloaded: 1800
Downloaded: 1900
Downloaded: 2000
Downloaded: 2100
Downloaded: 2200
Downloaded: 2300
Downloaded: 2400
Downloaded: 2500
Downloaded: 2600
Downloaded: 2700
Downloaded: 2800
Downloaded: 2900
Downloaded: 3000
Downloaded: 3100
Downloaded: 3200
Downloaded: 3300
Downloaded: 3400
Error: 502

In [77]:
recipes

[{'Unnamed: 0': 0,
  'title': 'No-Bake Nut Cookies',
  'ingredients': '["1 c. firmly packed brown sugar", "1/2 c. evaporated milk", "1/2 tsp. vanilla", "1/2 c. broken nuts (pecans)", "2 Tbsp. butter or margarine", "3 1/2 c. bite size shredded rice biscuits"]',
  'directions': '["In a heavy 2-quart saucepan, mix brown sugar, nuts, evaporated milk and butter or margarine.", "Stir over medium heat until mixture bubbles all over top.", "Boil and stir 5 minutes more. Take off heat.", "Stir in vanilla and cereal; mix well.", "Using 2 teaspoons, drop and shape into 30 clusters on wax paper.", "Let stand until firm, about 30 minutes."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=44874',
  'source': 'Gathered',
  'NER': '["brown sugar", "milk", "vanilla", "nuts", "butter", "bite size shredded rice biscuits"]'},
 {'Unnamed: 0': 1,
  'title': "Jewell Ball'S Chicken",
  'ingredients': '["1 small jar chipped beef, cut up", "4 boned chicken breasts", "1 can cream of mushroom soup", "1 carton sour cream"]',
  'directions': '["Place chipped beef on bottom of baking dish.", "Place chicken on top of beef.", "Mix soup and cream together; pour over chicken. Bake, uncovered, at 275\\u00b0 for 3 hours."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=699419',
  'source': 'Gathered',
  'NER': '["beef", "chicken breasts", "cream of mushroom soup", "sour cream"]'},
 {'Unnamed: 0': 2,
  'title': 'Creamy Corn',
  'ingredients': '["2 (16 oz.) pkg. frozen corn", "1 (8 oz.) pkg. cream cheese, cubed", "1/3 c. butter, cubed", "1/2 tsp. garlic powder", "1/2 tsp. salt", "1/4 tsp. pepper"]',
  'directions': '["In a slow cooker, combine all ingredients. Cover and cook on low for 4 hours or until heated through and cheese is melted. Stir well before serving. Yields 6 servings."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=10570',
  'source': 'Gathered',
  'NER': '["frozen corn", "cream cheese", "butter", "garlic powder", "salt", "pepper"]'},
 {'Unnamed: 0': 3,
  'title': 'Chicken Funny',
  'ingredients': '["1 large whole chicken", "2 (10 1/2 oz.) cans chicken gravy", "1 (10 1/2 oz.) can cream of mushroom soup", "1 (6 oz.) box Stove Top stuffing", "4 oz. shredded cheese"]',
  'directions': '["Boil and debone chicken.", "Put bite size pieces in average size square casserole dish.", "Pour gravy and cream of mushroom soup over chicken; level.", "Make stuffing according to instructions on box (do not make too moist).", "Put stuffing on top of chicken and gravy; level.", "Sprinkle shredded cheese on top and bake at 350\\u00b0 for approximately 20 minutes or until golden and bubbly."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=897570',
  'source': 'Gathered',
  'NER': '["chicken", "chicken gravy", "cream of mushroom soup", "shredded cheese"]'},
 {'Unnamed: 0': 4,
  'title': 'Reeses Cups(Candy)  ',
  'ingredients': '["1 c. peanut butter", "3/4 c. graham cracker crumbs", "1 c. melted butter", "1 lb. (3 1/2 c.) powdered sugar", "1 large pkg. chocolate chips"]',
  'directions': '["Combine first four ingredients and press in 13 x 9-inch ungreased pan.", "Melt chocolate chips and spread over mixture. Refrigerate for about 20 minutes and cut into pieces before chocolate gets hard.", "Keep in refrigerator."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=659239',
  'source': 'Gathered',
  'NER': '["peanut butter", "graham cracker crumbs", "butter", "powdered sugar", "chocolate chips"]'},
 {'Unnamed: 0': 5,
  'title': 'Cheeseburger Potato Soup',
  'ingredients': '["6 baking potatoes", "1 lb. of extra lean ground beef", "2/3 c. butter or margarine", "6 c. milk", "3/4 tsp. salt", "1/2 tsp. pepper", "1 1/2 c (6 oz.) shredded Cheddar cheese, divided", "12 sliced bacon, cooked, crumbled and divided", "4 green onion, chopped and divided", "1 (8 oz.) carton sour cream (optional)"]',
  'directions': '["Wash potatoes; prick several times with a fork.", "Microwave them with a wet paper towel covering the potatoes on high for 6-8 minutes.", "The potatoes should be soft, ready to eat.", "Let them cool enough to handle.", "Cut in half lengthwise; scoop out pulp and reserve.", "Discard shells.", "Brown ground beef until done.", "Drain any grease from the meat.", "Set aside when done.", "Meat will be added later.", "Melt butter in a large kettle over low heat; add flour, stirring until smooth.", "Cook 1 minute, stirring constantly. Gradually add milk; cook over medium heat, stirring constantly, until thickened and bubbly.", "Stir in potato, ground beef, salt, pepper, 1 cup of cheese, 2 tablespoons of green onion and 1/2 cup of bacon.", "Cook until heated (do not boil).", "Stir in sour cream if desired; cook until heated (do not boil).", "Sprinkle with remaining cheese, bacon and green onions."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=20115',
  'source': 'Gathered',
  'NER': '["baking potatoes", "extra lean ground beef", "butter", "milk", "salt", "pepper", "Cheddar cheese", "bacon", "green onion", "sour cream"]'},
 {'Unnamed: 0': 6,
  'title': 'Rhubarb Coffee Cake',
  'ingredients': '["1 1/2 c. sugar", "1/2 c. butter", "1 egg", "1 c. buttermilk", "2 c. flour", "1/2 tsp. salt", "1 tsp. soda", "1 c. buttermilk", "2 c. rhubarb, finely cut", "1 tsp. vanilla"]',
  'directions': '["Cream sugar and butter.", "Add egg and beat well.", "To creamed butter, sugar and egg, add alternately buttermilk with mixture of flour, salt and soda.", "Mix well.", "Add rhubarb and vanilla.", "Pour into greased 9 x 13-inch pan and add Topping."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=210288',
  'source': 'Gathered',
  'NER': '["sugar", "butter", "egg", "buttermilk", "flour", "salt", "soda", "buttermilk", "rhubarb", "vanilla"]'},
 {'Unnamed: 0': 7,
  'title': 'Scalloped Corn',
  'ingredients': '["1 can cream-style corn", "1 can whole kernel corn", "1/2 pkg. (approximately 20) saltine crackers, crushed", "1 egg, beaten", "6 tsp. butter, divided", "pepper to taste"]',
  'directions': '["Mix together both cans of corn, crackers, egg, 2 teaspoons of melted butter and pepper and place in a buttered baking dish.", "Dot with remaining 4 teaspoons of butter.", "Bake at 350\\u00b0 for 1 hour."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=876969',
  'source': 'Gathered',
  'NER': '["cream-style corn", "whole kernel corn", "crackers", "egg", "butter", "pepper"]'},
 {'Unnamed: 0': 8,
  'title': "Nolan'S Pepper Steak",
  'ingredients': '["1 1/2 lb. round steak (1-inch thick), cut into strips", "1 can drained tomatoes, cut up (save liquid)", "1 3/4 c. water", "1/2 c. onions", "1 1/2 Tbsp. Worcestershire sauce", "2 green peppers, diced", "1/4 c. oil"]',
  'directions': '["Roll steak strips in flour.", "Brown in skillet.", "Salt and pepper.", "Combine tomato liquid, water, onions and browned steak. Cover and simmer for one and a quarter hours.", "Uncover and stir in Worcestershire sauce.", "Add tomatoes, green peppers and simmer for 5 minutes.", "Serve over hot cooked rice."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=375254',
  'source': 'Gathered',
  'NER': '["tomatoes", "water", "onions", "Worcestershire sauce", "green peppers", "oil"]'},
 {'Unnamed: 0': 9,
  'title': 'Millionaire Pie',
  'ingredients': '["1 large container Cool Whip", "1 large can crushed pineapple", "1 can condensed milk", "3 lemons", "1 c. pecans", "2 graham cracker crusts"]',
  'directions': '["Empty Cool Whip into a bowl.", "Drain juice from pineapple.", "Mix Cool Whip and pineapple.", "Add condensed milk.", "Squeeze lemons, remove seeds and add to Cool Whip and pineapple.", "Chop nuts into small pieces and add to mixture.", "Stir all ingredients together and mix well.", "Pour into a graham cracker crust.", "Use top from crust to cover top of pie.", "Chill overnight.", "Makes 2 pies."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=794547',
  'source': 'Gathered',
  'NER': '["pineapple", "condensed milk", "lemons", "pecans", "graham cracker crusts"]'},
 {'Unnamed: 0': 10,
  'title': 'Double Cherry Delight',
  'ingredients': '["1 (17 oz.) can dark sweet pitted cherries", "1/2 c. ginger ale", "1 (6 oz.) pkg. Jell-O cherry flavor gelatin", "2 c. boiling water", "1/8 tsp. almond extract", "1 c. miniature marshmallows"]',
  'directions': '["Drain cherries, measuring syrup.", "Cut cherries in half.", "Add ginger ale and enough water to syrup to make 1 1/2 cups.", "Dissolve gelatin in boiling water.", "Add measured liquid and almond extract. Chill until very thick.", "Fold in marshmallows and the cherries. Spoon into 6-cup mold.", "Chill until firm, at least 4 hours or overnight.", "Unmold.", "Makes about 5 1/3 cups."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=703381',
  'source': 'Gathered',
  'NER': '["dark sweet pitted cherries", "ginger ale", "flavor gelatin", "boiling water", "almond extract", "marshmallows"]'},
 {'Unnamed: 0': 11,
  'title': 'Buckeye Candy',
  'ingredients': '["1 box powdered sugar", "8 oz. soft butter", "1 (8 oz.) peanut butter", "paraffin", "12 oz. chocolate chips"]',
  'directions': '["Mix sugar, butter and peanut butter.", "Roll into balls and place on cookie sheet.", "Set in freezer for at least 30 minutes. Melt chocolate chips and paraffin in double boiler.", "Using a toothpick, dip balls 3/4 of way into chocolate chip and paraffin mixture to make them look like buckeyes."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=886785',
  'source': 'Gathered',
  'NER': '["powdered sugar", "butter", "peanut butter", "paraffin", "chocolate chips"]'},
 {'Unnamed: 0': 12,
  'title': 'Quick Barbecue Wings',
  'ingredients': '["chicken wings (as many as you need for dinner)", "flour", "barbecue sauce (your choice)"]',
  'directions': '["Clean wings.", "Flour and fry until done.", "Place fried chicken wings in microwave bowl.", "Stir in barbecue sauce.", "Microwave on High (stir once) for 4 minutes."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=768311',
  'source': 'Gathered',
  'NER': '["chicken", "flour", "barbecue sauce"]'},
 {'Unnamed: 0': 13,
  'title': 'Taco Salad Chip Dip',
  'ingredients': '["8 oz. Ortega taco sauce", "8 oz. sour cream", "8 oz. cream cheese", "1 lb. ground beef", "1 pkg. taco seasoning", "shredded lettuce", "1 large diced tomato", "1 medium diced onion", "1 large diced green pepper", "shredded Colby or Cheddar cheese"]',
  'directions': '["Mix taco sauce, sour cream and cream cheese.", "Spread on pizza pan.", "Brown meat.", "Drain off fat and add taco seasoning.", "Spread over cream mixture.", "Layer with raw vegetables.", "Top with cheese. Serve with chips."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=806409',
  'source': 'Gathered',
  'NER': '["taco sauce", "sour cream", "cream cheese", "ground beef", "taco seasoning", "shredded lettuce", "tomato", "onion", "green pepper", "Cheddar cheese"]'},
 {'Unnamed: 0': 14,
  'title': 'Pink Stuff(Frozen Dessert)  ',
  'ingredients': '["1 can pie filling (cherry or strawberry)", "1 can crushed pineapple, drained", "1 can sweetened condensed milk", "1 (8 oz.) container thawed whipped topping", "2 Tbsp. lemon juice"]',
  'directions': '["Mix all ingredients together.", "Pour into a 9 x 13-inch pan. Freeze until firm.", "Allow to set out approximately 15 minutes before serving."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=982483',
  'source': 'Gathered',
  'NER': '["pie filling", "pineapple", "condensed milk", "lemon juice"]'},
 {'Unnamed: 0': 15,
  'title': 'Fresh Strawberry Pie',
  'ingredients': '["1 baked pie shell", "1 qt. cleaned strawberries", "1 1/2 c. water", "4 Tbsp. cornstarch", "1 c. sugar", "1/8 tsp. salt", "4 Tbsp. strawberry jello"]',
  'directions': '["Mix water, cornstarch, sugar and salt in saucepan.", "Stir constantly and boil until thick and clear.", "Remove from heat and stir in jello.", "Set aside to cool.", "But don\'t allow it to set. Layer strawberries in baked crust.", "Pour cooled glaze over. Continue layering berries and glaze.", "Refrigerate.", "Serve with whipped cream."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=161321',
  'source': 'Gathered',
  'NER': '["shell", "cleaned strawberries", "water", "cornstarch", "sugar", "salt", "strawberry jello"]'},
 {'Unnamed: 0': 16,
  'title': 'Easy German Chocolate Cake',
  'ingredients': '["1/2 pkg. chocolate fudge cake mix without pudding or 1 Jiffy mix", "1/2 pkg. white cake mix without pudding or 1 Jiffy mix", "1/4 c. Wesson oil"]',
  'directions': '["Mix according to directions and add oil.", "Bake in 9 x 13-inch pan."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=983179',
  'source': 'Gathered',
  'NER': '["chocolate fudge cake", "white cake", "Wesson oil"]'},
 {'Unnamed: 0': 17,
  'title': 'Broccoli Salad',
  'ingredients': '["1 large head broccoli (about 1 1/2 lb.)", "10 slices bacon, cooked and crumbled", "5 green onions, sliced or 1/4 c. chopped red onion", "1/2 c. raisins", "1 c. mayonnaise", "2 Tbsp. vinegar", "1/4 c. sugar"]',
  'directions': '["Trim off large leaves of broccoli and remove the tough ends of lower stalks. Wash the broccoli thoroughly. Cut the florets and stems into bite-size pieces. Place in a large bowl. Add bacon, onions and raisins. Combine remaining ingredients, stirring well. Add dressing to broccoli mixture and toss gently. Cover and refrigerate 2 to 3 hours. Makes about 6 servings."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=50992',
  'source': 'Gathered',
  'NER': '["broccoli", "bacon", "green onions", "raisins", "mayonnaise", "vinegar", "sugar"]'},
 {'Unnamed: 0': 18,
  'title': 'Strawberry Whatever',
  'ingredients': '["1 lb. frozen strawberries in juice", "1 small can crushed pineapple", "3 ripe bananas", "1 c. chopped pecans", "1 large pkg. strawberry Jell-O", "1 1/2 c. boiling water", "1 pt. sour cream"]',
  'directions': '["Mix Jell-O in boiling water.", "Add strawberries, pineapple, crushed bananas and nuts.", "Spread 1/2 mixture in 13 x 6 1/2-inch pan.", "Allow to gel in freezer 30 minutes.", "Add layer of sour cream, then remaining mixture on top.", "Gel and serve."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=718063',
  'source': 'Gathered',
  'NER': '["frozen strawberries", "pineapple", "bananas", "pecans", "strawberry", "boiling water", "sour cream"]'},
 {'Unnamed: 0': 19,
  'title': 'Eggless Milkless Applesauce Cake',
  'ingredients': '["3/4 c. sugar", "1/2 c. shortening", "1 1/2 c. applesauce", "3 level tsp. soda", "1 tsp. each: cinnamon, cloves and nutmeg", "2 c. sifted flour", "1 c. raisins", "1 c. nuts"]',
  'directions': '["Mix Crisco with applesauce, nuts and raisins.", "Sift dry ingredients and add.", "Mix well.", "Put in a greased and floured loaf pan or tube pan.", "Bake in loaf pan at 350\\u00b0 to 375\\u00b0 for 45 to 60 minutes, layer pan at 375\\u00b0 for 20 minutes or tube pan at 325\\u00b0 for 1 hour."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=343158',
  'source': 'Gathered',
  'NER': '["sugar", "shortening", "applesauce", "soda", "cinnamon", "flour", "raisins", "nuts"]'},
 {'Unnamed: 0': 20,
  'title': "Grandma Hanrath'S Banana Breadfort Collins, Colorado  ",
  'ingredients': '["1 c. sugar", "1/2 c. shortening", "2 eggs (add one at a time)", "1 tsp. salt", "2 tsp. soda", "2 c. flour", "1/4 c. nuts", "2 over-ripe bananas (chopped)"]',
  'directions': '["Cream sugar and shortening.", "Add eggs, salt and soda, then bananas and flour.", "Add nuts.", "Mix well.", "Bake in loaf pan at 350\\u00b0 for 1 hour."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=1072247',
  'source': 'Gathered',
  'NER': '["sugar", "shortening", "eggs", "salt", "soda", "flour", "nuts", "bananas"]'},
 {'Unnamed: 0': 21,
  'title': 'Chocolate Frango Mints',
  'ingredients': '["1 pkg. devil\'s food cake mix", "1 pkg. chocolate fudge pudding mix (instant)", "8 oz. sour cream", "3/4 c. water", "1/2 c. Wesson oil", "4 eggs", "6 oz. chopped Frango mints"]',
  'directions': '["Mix ingredients together for 5 minutes.", "Scrape bowl often. Last fold in chocolate chip mints.", "Bake at 350\\u00b0 for 35 to 40 minutes or until done (cake mix directions)."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=958474',
  'source': 'Gathered',
  'NER': '["cake mix", "chocolate fudge pudding", "sour cream", "water", "Wesson oil", "eggs", "Frango"]'},
 {'Unnamed: 0': 22,
  'title': 'Cuddy Farms Marinated Turkey',
  'ingredients': '["2 c. 7-Up or Sprite", "1 c. vegetable oil", "1 c. Kikkoman soy sauce", "garlic salt"]',
  'directions': '["Buy whole turkey breast; remove all skin and bones. Cut into pieces about the size of your hand. Pour marinade over turkey and refrigerate for at least 8 hours (up to 48 hours). The longer it marinates, the less cooking time it takes."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=9449',
  'source': 'Gathered',
  'NER': '["vegetable oil", "soy sauce", "garlic"]'},
 {'Unnamed: 0': 23,
  'title': 'Spaghetti Sauce To Can',
  'ingredients': '["1/2 bushel tomatoes", "1 c. oil", "1/4 c. minced garlic", "6 cans tomato paste", "3 peppers (2 sweet and 1 hot)", "1 1/2 c. sugar", "1/2 c. salt", "1 Tbsp. sweet basil", "2 Tbsp. oregano", "1 tsp. Italian seasoning"]',
  'directions': '["Cook ground or chopped peppers and onions in oil for 1/2 hour. Cook tomatoes and garlic as for juice.", "Put through the mill.", "(I use a food processor and do my tomatoes uncooked.", "I then add the garlic right to the juice.)", "Add peppers and onions to juice and remainder of ingredients.", "Cook approximately 1 hour.", "Put in jars and seal.", "Yields 7 quarts."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=1059279',
  'source': 'Gathered',
  'NER': '["tomatoes", "oil", "garlic", "tomato paste", "peppers", "sugar", "salt", "sweet basil", "oregano", "Italian seasoning"]'},
 {'Unnamed: 0': 24,
  'title': 'Prize-Winning Meat Loaf',
  'ingredients': '["1 1/2 lb. ground beef", "1 c. tomato juice", "3/4 c. oats (uncooked)", "1 egg, beaten", "1/4 c. chopped onion", "1/4 tsp. pepper", "1 1/2 tsp. salt"]',
  'directions': '["Mix well.", "Press firmly into an 8 1/2 x 4 1/2 x 2 1/2-inch loaf pan.", "Bake in preheated moderate oven.", "Bake at 350\\u00b0 for 1 hour.", "Let stand 5 minutes before slicing.", "Makes 8 servings."]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=923674',
  'source': 'Gathered',
  'NER': '["ground beef", "tomato juice", "oats", "egg", "onion", "pepper", "salt"]'},
 {'Unnamed: 0': 25,
  'title': 'Smothered Round Steak(Servings: 4)  ',
  'ingredients': '["2 lb. round steak", "1/2 tsp. ground black pepper", "1 tsp. ground white pepper", "1/2 c. vegetable oil", "2 bell peppers, chopped", "1 c. beef stock or water", "2 tsp. salt", "1 tsp. ground red pepper", "all-purpose flour (dredging)", "3 medium onions, chopped", "1 celery rib, chopped"]',
  'directions': '["Alex Patout says, \\"Smothering is a multipurpose Cajun technique that works wonders with everything from game to snap beans.", "It\'s similar to what the rest of the world knows as braising.", "The ingredients are briefly browned or sauteed, then cooked with a little liquid over a low heat for a long time.\\""]',
  'link': 'www.cookbooks.com/Recipe-Details.aspx?id=982859',
  'source': 'Gathered',
  'NER': '["steak", "ground black pepper", "ground white pepper", "vegetable oil", "bell peppers", "beef stock", "salt", "ground red pepper", "flour", "onions", "celery"]'},
 {'Unnamed: 0': 26,
  'title': 'Corral Barbecued Beef Steak Strips',
  'ingredients': '["2 lb. round steak 1/2 to 3/4-inch thick, sliced in strips 1/8-inch thick (or thinner) and 3 1/2 to 4-inches long (easily sliced if partially frozen)", "2 Tbsp. cooking oil", "1 can (15 oz.) tomato sauce", "1/3 c. water", "2 Tbsp. brown sugar", "1 Tbsp. prepared mustard", "1 tbsp. Worcestershire sauce", "1 medium sized onion, thinly sliced"]',

In [78]:
df = pd.DataFrame(recipes)

In [79]:
df.to_csv('dataset.csv')

In [80]:
df.head()

,Unnamed: 0,title,ingredients,directions,link,source,NER
0,0,No-Bake Nut Cookies,"[""1 c. firmly packed brown sugar"", ""1/2 c. eva...","[""In a heavy 2-quart saucepan, mix brown sugar...",www.cookbooks.com/Recipe-Details.aspx?id=44874,Gathered,"[""brown sugar"", ""milk"", ""vanilla"", ""nuts"", ""bu..."
1,1,Jewell Ball'S Chicken,"[""1 small jar chipped beef, cut up"", ""4 boned ...","[""Place chipped beef on bottom of baking dish....",www.cookbooks.com/Recipe-Details.aspx?id=699419,Gathered,"[""beef"", ""chicken breasts"", ""cream of mushroom..."
2,2,Creamy Corn,"[""2 (16 oz.) pkg. frozen corn"", ""1 (8 oz.) pkg...","[""In a slow cooker, combine all ingredients. C...",www.cookbooks.com/Recipe-Details.aspx?id=10570,Gathered,"[""frozen corn"", ""cream cheese"", ""butter"", ""gar..."
3,3,Chicken Funny,"[""1 large whole chicken"", ""2 (10 1/2 oz.) cans...","[""Boil and debone chicken."", ""Put bite size pi...",www.cookbooks.com/Recipe-Details.aspx?id=897570,Gathered,"[""chicken"", ""chicken gravy"", ""cream of mushroo..."
4,4,Reeses Cups(Candy),"[""1 c. peanut butter"", ""3/4 c. graham cracker ...","[""Combine first four ingredients and press in ...",www.cookbooks.com/Recipe-Details.aspx?id=659239,Gathered,"[""peanut butter"", ""graham cracker crumbs"", ""bu..."

In [81]:
df.tail()

,Unnamed: 0,title,ingredients,directions,link,source,NER
3395,3395,Noodle-Rice Casserole,"[""1/4 c. butter"", ""2 c. water"", ""3/4 oz. angel...","[""Melt butter in large skillet."", ""Add spaghet...",www.cookbooks.com/Recipe-Details.aspx?id=1048306,Gathered,"[""butter"", ""water"", ""hair spaghetti"", ""long gr..."
3396,3396,Apple Dip,"[""6 Granny Smith apples, sliced"", ""12 oz. crea...","[""Arrange apple slices around plate. Combine c...",www.cookbooks.com/Recipe-Details.aspx?id=558365,Gathered,"[""apples"", ""cream cheese"", ""sugar"", ""brown sug..."
3397,3397,3 Hour Sunday Rolls,"[""2 pkg. yeast"", ""2 whole eggs"", ""1/4 c. Wesso...","[""Mix the above 6 ingredients together."", ""Add...",www.cookbooks.com/Recipe-Details.aspx?id=963022,Gathered,"[""yeast"", ""eggs"", ""Wesson oil"", ""water"", ""suga..."
3398,3398,Slomgolian,"[""1 lb. ground beef"", ""1/2 c. chopped onion"", ...","[""Brown ground beef."", ""Saute onion and bell p...",www.cookbooks.com/Recipe-Details.aspx?id=8391,Gathered,"[""ground beef"", ""onion"", ""bell pepper"", ""mushr..."
3399,3399,Orange Sherbet Salad,"[""2 (3 oz.) pkg. orange gelatin"", ""2 c. hot wa...","[""Using juice from the mandarin oranges as par...",www.cookbooks.com/Recipe-Details.aspx?id=316249,Gathered,"[""orange gelatin"", ""water"", ""mandarin oranges""..."

In [82]:
df.shape

(3400, 7)

In [83]:
df.size

23800

In [84]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   3400 non-null   int64
 1   title        3400 non-null   str
 2   ingredients  3400 non-null   str
 3   directions   3400 non-null   str
 4   link         3400 non-null   str
 5   source       3400 non-null   str
 6   NER          3400 non-null   str
dtypes: int64(1), str(6)
memory usage: 2.2 MB

In [85]:
food_recipes = df["directions"].astype(str)

In [86]:
def convert_to_text(x):
    try:
        return " ".join(ast.literal_eval(x))
    except:
        return str(x)

recipes_txt = df["directions"].apply(convert_to_text)

In [87]:
recipes_txt

0       In a heavy 2-quart saucepan, mix brown sugar, ...
1       Place chipped beef on bottom of baking dish. P...
2       In a slow cooker, combine all ingredients. Cov...
3       Boil and debone chicken. Put bite size pieces ...
4       Combine first four ingredients and press in 13...
                              ...
3395    Melt butter in large skillet. Add spaghetti; c...
3396    Arrange apple slices around plate. Combine cre...
3397    Mix the above 6 ingredients together. Add enou...
3398    Brown ground beef. Saute onion and bell pepper...
3399    Using juice from the mandarin oranges as part ...
Name: directions, Length: 3400, dtype: str

In [88]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

recipes_cleaned = recipes_txt.apply(clean_text)

In [89]:
recipes_cleaned

0       in a heavy 2quart saucepan mix brown sugar nut...
1       place chipped beef on bottom of baking dish pl...
2       in a slow cooker combine all ingredients cover...
3       boil and debone chicken put bite size pieces i...
4       combine first four ingredients and press in 13...
                              ...
3395    melt butter in large skillet add spaghetti coo...
3396    arrange apple slices around plate combine crea...
3397    mix the above 6 ingredients together add enoug...
3398    brown ground beef saute onion and bell pepper ...
3399    using juice from the mandarin oranges as part ...
Name: directions, Length: 3400, dtype: str

In [90]:
corpus_text = " ".join(recipes_cleaned)
print(corpus_text)

in a heavy 2quart saucepan mix brown sugar nuts evaporated milk and butter or margarine stir over medium heat until mixture bubbles all over top boil and stir 5 minutes more take off heat stir in vanilla and cereal mix well using 2 teaspoons drop and shape into 30 clusters on wax paper let stand until firm about 30 minutes place chipped beef on bottom of baking dish place chicken on top of beef mix soup and cream together pour over chicken bake uncovered at 275 for 3 hours in a slow cooker combine all ingredients cover and cook on low for 4 hours or until heated through and cheese is melted stir well before serving yields 6 servings boil and debone chicken put bite size pieces in average size square casserole dish pour gravy and cream of mushroom soup over chicken level make stuffing according to instructions on box do not make too moist put stuffing on top of chicken and gravy level sprinkle shredded cheese on top and bake at 350 for approximately 20 minutes or until golden and bubbly combine first four ingredients and press in 13 x 9inch ungreased pan melt chocolate chips and spread over mixture refrigerate for about 20 minutes and cut into pieces before chocolate gets hard keep in refrigerator wash potatoes prick several times with a fork microwave them with a wet paper towel covering the potatoes on high for 68 minutes the potatoes should be soft ready to eat let them cool enough to handle cut in half lengthwise scoop out pulp and reserve discard shells brown ground beef until done drain any grease from the meat set aside when done meat will be added later melt butter in a large kettle over low heat add flour stirring until smooth cook 1 minute stirring constantly gradually add milk cook over medium heat stirring constantly until thickened and bubbly stir in potato ground beef salt pepper 1 cup of cheese 2 tablespoons of green onion and 12 cup of bacon cook until heated do not boil stir in sour cream if desired cook until heated do not boil sprinkle with remaining cheese bacon and green onions cream sugar and butter add egg and beat well to creamed butter sugar and egg add alternately buttermilk with mixture of flour salt and soda mix well add rhubarb and vanilla pour into greased 9 x 13inch pan and add topping mix together both cans of corn crackers egg 2 teaspoons of melted butter and pepper and place in a buttered baking dish dot with remaining 4 teaspoons of butter bake at 350 for 1 hour roll steak strips in flour brown in skillet salt and pepper combine tomato liquid water onions and browned steak cover and simmer for one and a quarter hours uncover and stir in worcestershire sauce add tomatoes green peppers and simmer for 5 minutes serve over hot cooked rice empty cool whip into a bowl drain juice from pineapple mix cool whip and pineapple add condensed milk squeeze lemons remove seeds and add to cool whip and pineapple chop nuts into small pieces and add to mixture stir all ingredients together and mix well pour into a graham cracker crust use top from crust to cover top of pie chill overnight makes 2 pies drain cherries measuring syrup cut cherries in half add ginger ale and enough water to syrup to make 1 12 cups dissolve gelatin in boiling water add measured liquid and almond extract chill until very thick fold in marshmallows and the cherries spoon into 6cup mold chill until firm at least 4 hours or overnight unmold makes about 5 13 cups mix sugar butter and peanut butter roll into balls and place on cookie sheet set in freezer for at least 30 minutes melt chocolate chips and paraffin in double boiler using a toothpick dip balls 34 of way into chocolate chip and paraffin mixture to make them look like buckeyes clean wings flour and fry until done place fried chicken wings in microwave bowl stir in barbecue sauce microwave on high stir once for 4 minutes mix taco sauce sour cream and cream cheese spread on pizza pan brown meat drain off fat and add taco seasoning spread over cream mixture layer with raw vegetables top with cheese serve with chips mix all ingredients together pour into a 9 x 13inch pan freeze until firm allow to set out approximately 15 minutes before serving mix water cornstarch sugar and salt in saucepan stir constantly and boil until thick and clear remove from heat and stir in jello set aside to cool but dont allow it to set layer strawberries in baked crust pour cooled glaze over continue layering berries and glaze refrigerate serve with whipped cream mix according to directions and add oil bake in 9 x 13inch pan trim off large leaves of broccoli and remove the tough ends of lower stalks wash the broccoli thoroughly cut the florets and stems into bitesize pieces place in a large bowl add bacon onions and raisins combine remaining ingredients stirring well add dressing to broccoli mixture and toss gently cover and refrigerate 2 to 3 hours makes about 6 servings mix jello in boiling water add strawberries pineapple crushed bananas and nuts spread 12 mixture in 13 x 6 12inch pan allow to gel in freezer 30 minutes add layer of sour cream then remaining mixture on top gel and serve mix crisco with applesauce nuts and raisins sift dry ingredients and add mix well put in a greased and floured loaf pan or tube pan bake in loaf pan at 350 to 375 for 45 to 60 minutes layer pan at 375 for 20 minutes or tube pan at 325 for 1 hour cream sugar and shortening add eggs salt and soda then bananas and flour add nuts mix well bake in loaf pan at 350 for 1 hour mix ingredients together for 5 minutes scrape bowl often last fold in chocolate chip mints bake at 350 for 35 to 40 minutes or until done cake mix directions buy whole turkey breast remove all skin and bones cut into pieces about the size of your hand pour marinade over turkey and refrigerate for at least 8 hours up to 48 hours the longer it marinates the less cooking time it takes cook ground or chopped peppers and onions in oil for 12 hour cook tomatoes and garlic as for juice put through the mill i use a food processor and do my tomatoes uncooked i then add the garlic right to the juice add peppers and onions to juice and remainder of ingredients cook approximately 1 hour put in jars and seal yields 7 quarts mix well press firmly into an 8 12 x 4 12 x 2 12inch loaf pan bake in preheated moderate oven bake at 350 for 1 hour let stand 5 minutes before slicing makes 8 servings alex patout says smothering is a multipurpose cajun technique that works wonders with everything from game to snap beans its similar to what the rest of the world knows as braising the ingredients are briefly browned or sauteed then cooked with a little liquid over a low heat for a long time brown strips in cooking oil pour off drippings combine tomato sauce water brown sugar mustard and worcestershire sauce add sauce and onion to meat slices cover and cook slowly stirring occasionally 30 minutes or until meat is tender serve over rice or buttered noodles yields 6 to 8 servings butter a square pan 8 x 8 x 2inches heat milk chocolate chips and unsweetened chocolate over low heat stirring constantly until chocolate is melted and mixture is smooth remove from heat stir in nuts and vanilla spread in pan in a large skillet brown the ground beef drain stir in taco mix kidney beans and salsa bring to a boil reduce heat and let simmer for about 5 minutes cut peppers in half and clean it put peppers in boiling water for 3 minutes drain spoon the meat mixture into the green pepper put pepper in an ungreased pan cover and bake at 350 degrees for 15 to 20 minutes or until peppers are crispy and filling is heated through top with tomatoes cheese and sour cream put flour into a large mixing bowl combine sugar milk salt and oil in a saucepan and heat to boiling remove from heat and let cool to lukewarm add yeast and mix well pour into flour and stir batter will be sticky roll out batter on a floured board and cut with biscuit cutter lightly brush tops with melted oleo and fold over place rolls on a cookie sheet put in a warm place and let rise for 1 hour bake at 350 for about 20 minutes yield 2 12 dozen in a 6quart punch bowl mix all of the cans of fruit juice and all clean and slice berries wash and slice apples leave peeling on apples dice apples slice bananas wash and cut grapes in half mix all together nuts or other fruit may be added double recipe for more chicken grease a 9 x 12inch cake pan spread cherry pie mix sift cake mix and spread it dry over the cherries top with ground nuts melt butter and pour over top bake 45 minutes in a 350 oven beat eggs salt and pepper until well blended stir in half and half potatoes and onions pour into wellgreased 8inch baking dish bake in a 400 oven for 35 to 40 minutes or until knife inserted in center comes out clean and potatoes are tender cool on rack 5 minutes cut into squares makes 4 large servings prepare macaroni and cheese as directed add drained tuna pimento and onion mix serve hot or cold drain artichokes and chop mix with mayonnaise and parmesan cheese after well mixed bake uncovered for 20 to 30 minutes at 350 serve with crackers mix together sour cream soup mix broccoli and half of cheese sprinkle remaining cheese on top bake at 350 for 30 minutes uncovered serve hot with vegetable crackers prepare spaghetti per package drain melt a little butter through it marinate overnight in salad supreme and zesty italian dressing just before serving add cucumbers tomatoes green peppers mushrooms olives or whatever your taste may want drain pears reserving juice bring juice to a boil stirring constantly remove from heat add gelatin stirring until dissolved let cool slightly coarsely chop pear halves combine cream cheese and yogurt beat at medium speed of electric mixer until smooth add gelatin and beat well stir in pears pour into an oiled 4cup mold or pyrex dish chill trim off green and pink parts of watermelon rind cut to 1inch cubes parboil until tender but not soft drain combine sugar vinegar oil of cloves and oil of cinnamon bring to boiling and pour over rind let stand overnight in the morning drain off syrup heat and put over rind the third morning heat rind and syrup seal in hot sterilized jars makes 8 pints oil of cinnamon and clove keeps rind clear and transparent remove chicken from bone use the broth mix the vegetables and macaroni add sugar salt and black pepper cook until all vegetables are tender over medium heat mix 3 tablespoons fat with granulated sugar add egg and beat until creamy mix flour baking powder and salt thoroughly add to sugar mixture alternately with milk add vanilla spread batter evenly in a greased 8inch square baking pan mix brown sugar and cinnamon and sprinkle over batter dot with 2 tablespoons fat bake at 350 moderate oven for 25 to 30 minutes mix flour sugar baking powder soda and salt together cut in margarine dissolve yeast in warm water stir into buttermilk and add to dry mixture cover and chill dip marshmallows in melted margarine roll in candy wrap a crescent triangle around each marshmallow completely covering the marshmallow and square edges of dough tightly to seal dip in margarine and place in a greased muffin tin bake at 375 for 10 to 15 minutes remove from pan mix ingredients and spread into 2 greased pizza pans bake at 350 for 1520 minutes mix together and bake in 9 x 13inch pan at 350 for 25 to 30 minutes top should spring back when touched lightly do not overbake cool completely then spread with mint layer stir the ingredients together and put in a greased and floured loaf pan bake at 425 degrees for 50 minutes drizzle melted butter on top melt margarine in skillet saute onions and celery remove from heat stir in flour and curry powder drain mushrooms and keep juice add water to juice to make 12 cup liquid stir liquid and soup into flour mixture add mushrooms cook until thick arrange broccoli and cubed chicken in a large baking dish spoon sauce over chicken top with grated cheese bake in a 350 oven for about 20 minutes or in microwave until cheese is melted sift flour baking powder and salt together cream together butter and sugar add egg yolks and vanilla beat until light and fluffy mix in sifted dry ingredients shape into 1inch balls push wooden spoon handle through center twist shape into rings dip each cookie into candies place on lightly greased baking sheets bake in 375 oven for 10 to 12 minutes or until golden brown cool on racks serves 2 dozen lightly brown beef in soup pot drain off excess fat stir in tomatoes tomato sauce water frozen vegetables soup mix and sugar bring to a boil reduce heat and simmer for 20 minutes serve dice chicken mix all ingredients together let sit overnight bake 1 12 hours at 375 in a large bowl combine cabbage carrot green pepper and onion or can use package of slaw mix purchased from store heat oven to 500 place fillets in single layer in baking dish 13 12 x 9 x 2inch stir together remaining ingredients except pepper rings spoon over fillets bake 5 to 8 minutes or until fish flakes easily with fork remove fillets to warm platter garnish with green pepper rings makes 4 to 6 servings mix together all of sugar salad oil vinegar and water until sugar is dissolved pour over beans and let stand overnight in a bowl mix corns sour cream corn bread mix and melted margarine pour into a greased 8 x 8 x 2inch pan bake at 350 for 50 minutes brown beef with onion and seasonings and combine in a 1 12quart casserole with soup water and noodles place cheese around edges bake at 350 for 30 minutes combine all ingredients and cook uncovered over low heat until cabbage is crisptender about 20 minutes mix together and carefully add 1 pound lump crab meat mix ahead of time and refrigerate so they will hold together better mix together cream cheese and mayonnaise spread on to a large platter or two dinner plates freeze for 15 minutes spread taco sauce evenly on top layer remaining ingredients in the written order serve with tortilla chips cream together the butter and peanut butter add the remaining ingredients mix and form into balls best to mix with your hands and chill several hours even a day mix together spread in a buttered pan bake for 30 minutes at 275 while still hot sift 1 box of powdered sugar into it drop by teaspoons on waxed paper let dry if it seems set on bottom turn over and let it continue to dry mix together cake mix 2 eggs and melted oleo put in greased 9 x 13inch pan put chopped nuts on top of mixture mix together 2 eggs cream cheese and powdered sugar add on top of first mixture bake 15 minutes at 325 then bake 20 minutes at 350 drain pineapple and reserve juice cut bananas in chunks like pineapple mix all ingredients together in baking dish cover and bake at 350 for 2 12 hours bake the last 45 minutes uncovered to brown top of chicken cream the cream cheese add the milk and beat smooth add lemon juice pineapple and nuts beat well pour into graham cracker crust and chill slice in small servings very rich and top with dollop of cool whip mix all ingredients form in small balls and roll in chopped peanuts keep refrigerated puree peaches in a blender add remaining ingredients blend and pour in container and freeze can also use blueberries or cherries mix ingredients and press 23 mixture in bottom of square baking dish a bowl that has the same diameter top and bottom may be used 1 12 to 2quart size sift together the flour soda and salt set aside combine shortening and sugar in a bowl beat until creamy add egg yolks beat well combine cocoa water and vanilla to make 1 cup mix well add to batter add flour mixture alternately with milk beat well after each addition set aside beat egg whites until stiff peaks form when beater is lifted fold into batter bake in two 9inch greased cake pans at 375 for 30 minutes combine and cook first 6 ingredients bring to boil and boil 5 minutes cool add sifted dry ingredients to apple mixture stir and blend only add nuts pour into greased and floured tube pan bake 1 hour at 350 serves 16 peel and dice potatoes place in bowl of cold salted water drain potatoes and dry on paper towels mix 12 cup butter onions soup sour cream and cheese stir well add potatoes to mixture and pour into a 2 12quart casserole dish crush cornflakes mix with remaining butter sprinkle cornflakes and butter on top of potato mixture bake at 350 for 50 minutes mix vanilla wafer crumbs with butter stir well together the sugar syrup and water allow to boil without stirring until it forms a hard ball in cold water pour this over stiffly beaten egg whites beating constantly cool add vanilla and nuts beat until cool and thick enough to set pour into a buttered platter or drop by teaspoons on waxed paper mix 12 cup of sugar and cinnamon spread on apples mix 14 cup sugar flour salt cornflake crumbs and oleo spread mixture on apples mix sausage and cheese together add bisquick and mix thoroughly roll into medium size balls bake at 350 for 15 minutes or until golden brown add enough liquid to chicken soup and consomme to make 4 cups of water season with salt and pepper cook at 350 for 1 hour brown celery onions and ground beef in butter add vinegar lemon juice brown sugar mustard salt pepper catsup and water simmer for 30 minutes in saucepan slowly stir the chicken broth into cornstarch cook stirring constantly until slightly thickened slowly pour in the well beaten egg stir once gently remove from heat garnish with sliced green onion makes 4 servings simmer all of the ingredients strain into warmed mugs and top with a dash of nutmeg this recipe can be doubled many times according to the number of guests present combine first 4 ingredients in a small bowl stir well and set aside place chicken between 2 sheets of waxed paper or heavy duty plastic wrap and flatten to 14inch thickness using meat mallet or rolling pin coat grill rack with cooking spray place on grill over coals place chicken on rack and cook 4 minutes on each side basting frequently with soy sauce mixture transfer chicken to a serving platter and garnish with green onion if desired yields 4 servings about 200 calories saute together first 5 ingredients in a separate 9 x 12inch pan mix bread eggs and milk put pieces of bread into pan add your vegetables then your eggs place in refrigerator overnight at least 8 hours add cheddar cheese before cooking bake at 350 for 1 hour in food processor or blender grind cranberries apple and orange mix with sugar and set aside prepare gelatin according to package directions using 14 cup less of cold water chill until it begins to thicken add cranberry mixture and nuts mix well pour into a mold if desired or leave in a bowl and stir before serving chill until set can even be made a day ahead keeps well in refrigerator for a few days put in a covered 1 12quart dish bake 1 hour at 350 mix cream cheese margarine and sugar add fruit and walnuts whip cream and fold into fruit and cream cheese mixture pour into round mold freeze 6 hours remove from mold shortly before serving makes 12 servings dice tomatoes and peppers combine all ingredients in top of double boiler for 30 minutes serve hot over corn chips sift first 5 ingredients together in a bowl mix egg and milk together add to dry ingredients beat until smooth hold finger over bottom of a funnel pour in some batter remove finger to let batter drop drop batter in a spiral motion into pan filled with 1 inch of hot oil 375 fry until golden brown turning once remove from pan drain on a paper towel sprinkle with powdered sugar and serve hot in large bowl put confectioners sugar cocoa and chopped nuts in saucepan put margarine and velveeta melt and add vanilla pour hot mixture over sugar mixture mix quickly and pour into buttered cookie sheet cool and cut into squares cook squash onions and carrots until tender mash melt butter in pan stir in stuffing until all is coated drain all water from squash stir in sour cream and soup place in a greased baking dish a layer of squash and a layer of stuffing bake at 350 for 35 minutes com

In [91]:
corpus_text[:2000]

'in a heavy 2quart saucepan mix brown sugar nuts evaporated milk and butter or margarine stir over medium heat until mixture bubbles all over top boil and stir 5 minutes more take off heat stir in vanilla and cereal mix well using 2 teaspoons drop and shape into 30 clusters on wax paper let stand until firm about 30 minutes place chipped beef on bottom of baking dish place chicken on top of beef mix soup and cream together pour over chicken bake uncovered at 275 for 3 hours in a slow cooker combine all ingredients cover and cook on low for 4 hours or until heated through and cheese is melted stir well before serving yields 6 servings boil and debone chicken put bite size pieces in average size square casserole dish pour gravy and cream of mushroom soup over chicken level make stuffing according to instructions on box do not make too moist put stuffing on top of chicken and gravy level sprinkle shredded cheese on top and bake at 350 for approximately 20 minutes or until golden and bubbly combine first four ingredients and press in 13 x 9inch ungreased pan melt chocolate chips and spread over mixture refrigerate for about 20 minutes and cut into pieces before chocolate gets hard keep in refrigerator wash potatoes prick several times with a fork microwave them with a wet paper towel covering the potatoes on high for 68 minutes the potatoes should be soft ready to eat let them cool enough to handle cut in half lengthwise scoop out pulp and reserve discard shells brown ground beef until done drain any grease from the meat set aside when done meat will be added later melt butter in a large kettle over low heat add flour stirring until smooth cook 1 minute stirring constantly gradually add milk cook over medium heat stirring constantly until thickened and bubbly stir in potato ground beef salt pepper 1 cup of cheese 2 tablespoons of green onion and 12 cup of bacon cook until heated do not boil stir in sour cream if desired cook until heated do not boil sprinkle with remaini'

In [92]:
with open("corpus.txt", "w", encoding="utf-8") as f:
    f.write(corpus_text)

In [94]:
MAX_RECIPES = 1000
MAX_WORDS = 200
SEQ_LEN = 20

# Create input sequences and targets
sequences = []
targets = []

tokenizer = Tokenizer()


for text in recipes[:MAX_RECIPES]:

    # Convert recipe text into word IDs
    words = tokenizer.texts_to_sequences([text])[0]

    # Limit recipe to 200 words
    words = words[:MAX_WORDS]

    # Create 20-word input → next-word target
    for i in range(SEQ_LEN, len(words)):
        sequences.append(words[i-SEQ_LEN:i])
        targets.append(words[i])

# Convert to NumPy arrays
X = np.array(sequences, dtype=np.int32)
y = np.array(targets, dtype=np.int32)

# Check the data
print("Number of samples:", len(X))
print("X shape:", X.shape)
print("y shape:", y.shape)
print("Vocabulary size:", total_words)

AttributeError: 'dict' object has no attribute 'lower'

In [ ]:
y = to_categorical(y, num_classes=total_words)

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (157492, 176)
y shape: (157492, 3368)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (125993, 176)
X_test : (31499, 176)
y_train: (125993, 3368)
y_test : (31499, 3368)

In [ ]:
model = Sequential([
    Embedding(
        input_dim=total_words,
        output_dim=128
    ),

    LSTM(150),

    Dropout(0.2),

    Dense(total_words, activation="softmax")
])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [ ]:
y = to_categorical(y, num_classes=total_words)

MemoryError: Unable to allocate 13.0 TiB for an array with shape (530433056, 3368) and data type float64

In [ ]:
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True,
    verbose=1
)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=128,
    validation_split=0.1,
    callbacks=[early_stopping]
)